apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: notes-app
spec:
  type: ClusterIP # Though this is the default one
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
